### ISSUE TITLE
[Bug]: Crash with More culling

### ISSUE THREAD

**Issue by coco875** [MinecraftschurliMods/Bibliocraft-Legacy#2]
### Describe the bug

when I try to place a table it crash.

### Steps to Reproduce

1. have more culling and bibliocraft
2. try place a table
3. see the crash

### Expected behavior

to not crash

### Screenshots

![image](https://github.com/user-attachments/assets/2e558c81-bff7-4698-a0d3-7267f69bd843)

### Version

1.20.4-1.0.0

### NeoForge Version

21.1.72

### Other Mods

ActuallyAdditions-1.3.2+mc1.21.1.jar
AI-Improvements-1.21-0.5.3.jar
allthewizardgear-1.21-1.1.6.jar
alternate_current-mc1.21-1.9.0.jar
appliedenergistics2-19.0.23-beta.jar
Applied-Mekanistics-1.6.1.jar
ars_additions-1.21.0-21.0.2.jar
ars_elemental-1.21.0-0.7.0.5.jar
ars_nouveau-1.21.0-5.1.0-all.jar
arstechnic-0.1.0.jar
athena-neoforge-1.21-4.0.1.jar
bclib-21.0.13.jar
bettercombat-neoforge-2.0.3+1.21.1.jar
better-end-21.0.11.jar
better_modlist-1.1.7.jar
better-nether-21.0.11.jar
bibliocraft-1.21.1-1.1.0.jar
bibliowoods-1.21.1-1.0.jar
c2me-fabric-mc1.21.1-0.3.0+alpha.0.290.jar
caelus-neoforge-7.0.1+1.21.1.jar
cloth-config-15.0.140-neoforge.jar
configuration-neoforge-1.21.1-3.1.0.jar
connector-2.0.0-beta.3+1.21.1-full.jar
ConnectorExtras-1.12.1+1.21.1.jar
CreativeCore_NEOFORGE_v2.12.17_mc1.21.1.jar
curios-neoforge-8.0.2+1.20.6.jar
curios-neoforge-9.1.4+1.21.0.jar
EclipticSeasons-1.21.1-neoforge-0.4.2-alpha.jar
emi-1.1.16+1.21.1+neoforge.jar
emi_enchanting-0.1.2+1.21+neoforge.jar
emi_loot-0.7.4+1.21+neoforge.jar
EuphoriaPatcher-0.3.4-neoforge.jar
ExtremeReactors2-1.21.1-2.4.11.jar
FancyBlockParticles-1.21.1-neoforge-21.1.0.1-beta.jar
FarmersDelight-1.21.1-1.2.4a.jar
FastWorkbench-1.21-9.1.2.jar
ferritecore-7.0.0-neoforge.jar
forgified-fabric-api-0.104.0+2.0.15+1.21.1.jar
FramedBlocks-10.2.0.jar
fzzy_config-0.5.4+1.21+neoforge.jar
gcyr-1.21.1-0.2.4.jar
geckolib-neoforge-1.21.1-4.6.6.jar
gregfluxology-0.0.1-modern.jar
gtceu-1.21.1-1.4.6.jar
ImmediatelyFast-NeoForge-1.2.21+1.21.1.jar
iris-neoforge-1.8.0-beta.5+mc1.21.1.jar
irons_spellbooks-1.21-3.7.1.jar
Jade-1.21.1-NeoForge-15.1.8.jar
jei-1.21.1-neoforge-19.21.0.246.jar
JustEnoughMekanismMultiblocks-1.21.1-7.1.jar
kotlinforforge-5.5.0-all.jar
lavender-0.1.13+1.21.jar
ldlib-neoforge-1.21.1-1.0.29.b.jar
lithium-neoforge-0.14.0-snapshot+mc1.21.1-build.88.jar
Mekanism-1.21.1-10.7.7.64.jar
MekanismAdditions-1.21.1-10.7.7.64.jar
mekanismcovers-1.0.1-BETA+1.21.jar
mekanismdelight-1.0.2-1.21.x.jar
MekanismGenerators-1.21.1-10.7.7.64.jar
MekanismLasers-1.21.1-1.1.6.jar
MekanismTools-1.21.1-10.7.7.64.jar
mekanism_turrets-2.0.9.jar
modernfix-neoforge-5.19.3+mc1.21.1.jar
Modern-Industrialization-2.2.25.jar
modonomicon-1.21.1-neoforge-1.108.1.jar
moonlight-1.21-2.14.32-neoforge.jar
moreculling-neoforge-1.21.1-1.0.0.jar
MoreMekanismProcessing-1.21.1-6.1.jar
ObsidianUI-neoforge-0.2.8+mc1.21.1.jar
occultism-1.21.1-neoforge-1.161.4.jar
oritech-0.9.1.jar
owo-lib-0.12.15+1.21.jar
particle_core-0.2.5+1.21+neoforge.jar
Patchouli-1.21-87-NEOFORGE.jar
Placebo-1.21.1-9.5.3.jar
player-animation-lib-forge-2.0.0-alpha1+1.21.jar
pmc-1.0.1.jar
polymorph-neoforge-1.0.6+1.21.1.jar
productivebees-1.21.1-13.6.1.jar
productivetrees-1.21.1-0.5.4.jar
railcraft-reborn-1.21.1-1.2.2.jar
reeses-sodium-options-neoforge-1.8.0-beta.4+mc1.21.1.jar
resourcefullib-neoforge-1.21-3.0.11.jar
rhino-2101.2.5-build.54.jar
RootsClassic-1.21.1-1.5.4.jar
servercore-neoforge-1.5.5+1.21.1.jar
SmartBrainLib-neoforge-1.21.1-1.16.1.jar
sodium-extra-neoforge-0.6.0-beta.3+mc1.21.1.jar
sodium-neoforge-0.6.0-beta.2+mc1.21.1.jar
the_bumblezone-7.7.3+1.21.1-neoforge.jar
theurgy-1.21.1-neoforge-1.56.0.jar
tt20-0.7.0+mc1.21.jar
vmp-fabric-mc1.21.1-0.2.0+beta.7.168-all.jar
waterframes-NEOFORGE-mc1.21.1-v2.1.6b.jar
watermedia-2.0.75.jar
worldweaver-21.0.13.jar
ZeroCore2-1.21.1-2.4.11.jar

### Log

```shell
https://mclo.gs/mhny8MT
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coco875** [comment]
in moreculling.toml change `useOnModdedBlocksByDefault` to false fix the problem

**Comment by Minecraftschurli** [comment]
does it happen with only the 2 mods? If so please provide a link to their github so we can check what is breaking

**Comment by coco875** [comment]
[crash-2024-11-12_16.25.13-client.txt](https://github.com/user-attachments/files/17718724/crash-2024-11-12_16.25.13-client.txt)
the crash report with only more culling and bibliocraft, and the github: https://github.com/fxmorin/moreculling

**Comment by IchHabeHunger54** [comment]
Hello, sorry for taking so long to get back to you.

I've contacted the More Culling dev, and hopefully we can work this issue out.

**Comment by coco875** [comment]
ok, thanks, like I said in moreculling.toml change useOnModdedBlocksByDefault to false fix the problem so it doesn't really block me

**Comment by IchHabeHunger54** [comment]
Fixed on More Culling's end, please update that mod.
