### ISSUE TITLE
[Bug]: Tape measure issues

### ISSUE THREAD

**Issue by Hiranus** [MinecraftschurliMods/Bibliocraft-Legacy#4]
### Describe the bug

![image](https://github.com/user-attachments/assets/71404347-7e46-40e3-8c8d-3abb7a092118)
Just how is that calculated? 
Also please add some sort of indicator as to what was actually measured.

### Steps to Reproduce

Use tape measure to measure 2 random places.

### Expected behavior

Tape measure provides the correct distance and shows some sort of visual representation of the area that was measured.

### Version

1.20.4-1.0.0

### NeoForge Version

I'm actually running version 1.1.1 with MC 1.21.1 and NeoForge 21.1.73

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IchHabeHunger54** [comment]
Hello, thank you for the report and sorry for taking so long. Version 1.2.1 has just been released, fixing this issue.
